### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by yavisht** [waldekmastykarz/docker-spfx#1]
Using MacOs

Command used to install:
docker run -h spfx -it --rm --name ${PWD##*/} -v $PWD:/usr/app/spfx -p 5432:5432 -p 4321:4321 -p 35729:35729 waldekm/spfx

Let's create a new SharePoint solution.
? What is your solution name? spfx
? Where do you want to place the files? Use the current folder
? What is your webpart name? HelloWorld
? What is your webpart description? HelloWorld description
? What framework would you like to start with? React
   create package.json
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EACCES: permission denied, open '/usr/app/spfx/package.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.writeFileSync (fs.js:1333:33)
    at write (/usr/local/lib/node_modules/@microsoft/generator-sharepoint/node_modules/mem-fs-editor/lib/actions/commit.js:14:6)
    at DestroyableTransform._transform (/usr/local/lib/node_modules/@microsoft/generator-sharepoint/node_modules/mem-fs-editor/lib/actions/commit.js:43:7)
    at DestroyableTransform.Transform._read (/usr/local/lib/node_modules/@microsoft/generator-sharepoint/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/usr/local/lib/node_modules/@microsoft/generator-sharepoint/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/usr/local/lib/node_modules/@microsoft/generator-sharepoint/node_modules/readable-stream/lib/_stream_writable.js:347:64)
    at writeOrBuffer (/usr/local/lib/node_modules/@microsoft/generator-sharepoint/node_modules/readable-stream/lib/_stream_writable.js:336:5)
    at DestroyableTransform.Writable.write (/usr/local/lib/node_modules/@microsoft/generator-sharepoint/node_modules/readable-stream/lib/_stream_writable.js:274:11)
spfx@spfx:/usr/app/spfx$

**Comment by waldekmastykarz** [comment]
Have you shared the directory mapped in the volume in Docker's settings?

**Comment by praveenbattula** [comment]
I see this issue in Windows OS. I have shared the drive. But the issue exists when I run yo @microsoft/sharepoint. I tried to run the yo command with yarn too. But, same issue. 

? Which framework would you like to use? React
Overwriting an existing "Teams Manifest

   create package.json
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EACCES: permission denied, open '/usr/app/spfx/package.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.writeFileSync (fs.js:1299:33)
    at write (/usr/local/lib/node_modules/@microsoft/generator-sharepoint/node_modules/mem-fs-editor/lib/actions/commit.js:14:6)
    at DestroyableTransform._transform (/usr/local/lib/node_modules/@microsoft/generator-sharepoint/node_modules/mem-fs-editor/lib/actions/commit.js:43:7)
    at DestroyableTransform.Transform._read (/usr/local/lib/node_modules/@microsoft/generator-sharepoint/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/usr/local/lib/node_modules/@microsoft/generator-sharepoint/node_modules/readable-stream/lib/_stream_transform.js:172:83)
    at doWrite (/usr/local/lib/node_modules/@microsoft/generator-sharepoint/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/usr/local/lib/node_modules/@microsoft/generator-sharepoint/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at DestroyableTransform.Writable.write (/usr/local/lib/node_modules/@microsoft/generator-sharepoint/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at DestroyableTransform.ondata (/usr/local/lib/node_modules/@microsoft/generator-sharepoint/node_modules/readable-stream/lib/_stream_readable.js:619:20)

**Comment by waldekmastykarz** [comment]
Which version of the docker image and docker are you using?

**Comment by praveenbattula** [comment]
1.7.0 (the latest one).

**Comment by waldekmastykarz** [comment]
And which version of Docker for Windows?

**Comment by dmc91** [comment]
I'm having the same issue on Windows.

Docker for Windows version 2.0.0.3 using the latest docker image.

**Comment by carletto75** [comment]
same issue here

**Comment by rezmes** [comment]
OS: Windows 10

Docker Desktop v3.5.2 **setting > General > Use the WLS 2 based engine**  is ticked


Using _Windows Terminal_  which has been running as administrator, I ran this command in a Ubuntu terminal:

`docker run -it --rm --name ${PWD##*/} -v $PWD:/usr/app/spfx -p 5432:5432 -p 4321:4321 -p 35729:35729 waldekm/spfx:1.4.1`

And then after running the container, using this command: `npm -g ls -depth=0` checked it, but got this error: 


_npm ERR! invalid: minizlib@1.0.3 /usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minizlib_

![Screenshot 2021-07-12 133519](https://user-images.githubusercontent.com/19559077/125261202-4ae15880-e316-11eb-8531-474118712828.png)

After running `gulp serve` I got this error:


[10:06:01] Error - 'copy-static-assets' sub task errored after 14 s
 EPERM: operation not permitted, chmod '/usr/app/spfx/lib/webparts/scriptEditor/ScriptEditorWebPart.manifest.json'
{ Error: EPERM: operation not permitted, chmod '/usr/app/spfx/lib/webparts/scriptEditor/components/ScriptEditor.module.css'
  errno: -1,
  code: 'EPERM',
  syscall: 'chmod',
  path: '/usr/app/spfx/lib/webparts/scriptEditor/components/ScriptEditor.module.css' }
[10:06:01] Error - Unknown
 EPERM: operation not permitted, chmod '/usr/app/spfx/lib/webparts/scriptEditor/components/ScriptEditor.module.css'
{ Error: EPERM: operation not permitted, chmod '/usr/app/spfx/src/webparts/scriptEditor/components/ScriptEditor.module.scss.ts'
  errno: -1,
  code: 'EPERM',
  syscall: 'chmod',
  path: '/usr/app/spfx/src/webparts/scriptEditor/components/ScriptEditor.module.scss.ts' }
[10:06:01] Error - Unknown
 EPERM: operation not permitted, chmod '/usr/app/spfx/src/webparts/scriptEditor/components/ScriptEditor.module.scss.ts'
[10:06:01] ==================[ Finished ]==================
Warning - [spfx-serve] When serving in HTTPS mode, a PFX cert path or a cert path and a key path must be provided, or a dev certificate must be generated and trusted. If a SSL certificate isn't provided, a default, self-signed certificate will be used. Expect browser security warnings.
Error - 'copy-static-assets' sub task errored after 14 s
 EPERM: operation not permitted, chmod '/usr/app/spfx/lib/webparts/scriptEditor/ScriptEditorWebPart.manifest.json'
Error - Unknown
 EPERM: operation not permitted, chmod '/usr/app/spfx/lib/webparts/scriptEditor/components/ScriptEditor.module.css'
Error - Unknown
 EPERM: operation not permitted, chmod '/usr/app/spfx/src/webparts/scriptEditor/components/ScriptEditor.module.scss.ts'
[10:06:02] Project pnp-script-editor version: 1.0.0
[10:06:02] Build tools version: 3.2.7
[10:06:02] Node version: v8.9.4
[10:06:02] Total duration: 1.33 min
[10:06:02] Task warnings: 1
[10:06:02] Task errors: 5
[10:06:02] Error - 'undefined' errored after
 "orchestration aborted"
[10:06:02] Error - 'undefined' errored after
 "orchestration aborted"
 
![Screenshot 2021-07-12 144649](https://user-images.githubusercontent.com/19559077/125276300-52f4c480-e325-11eb-983e-58758ad4a064.png)


And finaly in browser I get this error:

manifests.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
sp-loader-assembly_en-us.js:16841 Beacon: To disable logging to the console set "window.disableBeaconLogToConsole = true" in the debug window
sp-loader-assembly_en-us.js:20952 Beacon: To disable logging to the console set "window.disableBeaconLogToConsole = true" in the debug window
workbenchInit.js:8 Uncaught TypeError: Cannot read property 'getManifests' of undefined
    at workbenchInit.js:8
sp-loader-assembly_en-us.js:5428 Uncaught (in promise) Error: ***Invalid preloaded data.
    at sp-loader-assembly_en-us.js:5428
DevTools failed to load source map: Could not load content for https://localhost:4321/node_modules/@microsoft/sp-webpart-workbench/node_modules/@microsoft/sp-loader/dist/sp-core-library_en-us.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
![Screenshot 2021-07-12 152311](https://user-images.githubusercontent.com/19559077/125276265-44a6a880-e325-11eb-9fcd-b0a8d845d178.png)

**Comment by waldekmastykarz** [comment]
Dependencies are not a part of the container. Could it be that there was a network issue or an issue with npm that would lead to the issue with minizlib you mentioned? Have you tried restoring the dependencies again?

**Comment by rezmes** [comment]
First, Thank you for the quick response.
Then, I tried to install npm again through npm `-g i npm@5.6.0`
I got this error:

npm WARN notice [SECURITY] npm has the following vulnerabilities: 4 low. Go here for more details: https://www.npmjs.com/advisories?search=npm&version=5.6.0 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minizlib
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/npm
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/npm/node_modules/tar/node_modules
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
npm ERR! path _/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minizlib_
npm ERR! code **EACCES**
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minizlib'
npm ERR!  { Error: EACCES: permission denied, access '/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minizlib'
npm ERR!   stack: 'Error: EACCES: permission denied, access \'/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minizlib\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minizlib' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/spfx/.npm/_logs/2021-07-12T14_05_30_402Z-debug.log

![Screenshot 2021-07-12 184250](https://user-images.githubusercontent.com/19559077/125302415-29e22d00-e341-11eb-9f63-7f40ed89403c.png)

**Comment by rezmes** [comment]
Today: >
From in the docker container: 
`git clone https://github.com/pnp/sp-dev-fx-webparts.git`
I got this error:
fatal: could not create work tree dir 'sp-dev-fx-webparts'.: Permission denied
![Screenshot 2021-07-13 091810](https://user-images.githubusercontent.com/19559077/125392455-70746d80-e3bb-11eb-8a88-b2264568a424.png)

**Comment by waldekmastykarz** [comment]
Have you granted Docker write access to the local folder you mounted as volume for the container?

**Comment by rezmes** [comment]
As far as I know, to make a read-only volume, we shall use ":ro" at the end of the path string (after "-v" switch), which obviously we didn't! I assume otherwise, Docker should have write access by default. But I am not sure how can I check it.
Besides, I am not sure if grant write access to the folder -in which volume is nested- is different from write access to the volume itself or not.

I even tried to make using id=1000 for the inner user - in this case "spfx" - (same as the user who ran docker), but no different.
Still, the problem persists. I appreciate your help in forward.

**Comment by waldekmastykarz** [comment]
In Docker desktop settings, have you included the path that you're mounting the volume to in the file sharing options under Preferences > Resources > File sharing?

**Comment by rezmes** [comment]
Since I had started Docker with wls 2, there was no "File sharing" option under the Resources. ( 
But even though, to see the result, I **unchecked General > Use the WSL 2 based engine** and restarted docker. Then I added this address: "c:\users\administrator" to File sharing. but again I got exactly same Error.

**Comment by shurick81** [comment]
I had a similar issue:

```
spfx@25d1b387f069:/usr/app/spfx$ gulp serve --nobrowser
Build target: DEBUG
[10:39:46] Using gulpfile /usr/app/spfx/gulpfile.js
[10:39:46] Starting 'serve'...
[10:39:46] Starting gulp
[10:39:46] Starting subtask 'spfx-serve'...
[10:39:46] [spfx-serve] To load your scripts, use this query string: ?debug=true&noredir=true&debugManifestsFile=https://localhost:4321/temp/manifests.js
[10:39:46] Starting server...
[10:39:46] Finished subtask 'spfx-serve' after 61 ms
[10:39:46] Starting subtask 'pre-copy'...
[10:39:46] Finished subtask 'pre-copy' after 15 ms
[10:39:46] Starting subtask 'copy-static-assets'...
[10:39:46] Starting subtask 'sass'...
[10:39:46] Server started https://localhost:4321
[10:39:46] LiveReload started on port 35729
[10:39:46] Running server
[10:39:46] Error - 'sass' sub task errored after 464 ms
 EACCES: permission denied, open '/usr/app/spfx/src/webparts/secretGenerator/components/SecretGenerator.module.scss.ts'
[10:39:48] Finished subtask 'copy-static-assets' after 2.05 s
^C[10:40:38] Server stopped
[10:40:38] The following tasks did not complete: serve
[10:40:38] Did you forget to signal async completion?
About to exit with code: 0
Process terminated before summary could be written, possible error in async code not continuing!
Trying to exit with exit code 1
```

I solved it via running `sudo chown -R 1001:1001` in the solution directory.

I actually was very confused and spent quite a lot of hours on troubleshooting because this file `src/webparts/secretGenerator/components/SecretGenerator.module.scss.ts` in fact does not exist, So the problem I had was not in the specific file but in the permissions to the whole `src` directory

**Comment by tor-axbit** [comment]
@shurick81 in which solution directory did you run `sudo chown -R 1001:1001 .` ?

**Comment by shurick81** [comment]
```
cd <project directory>
sudo chown -R 1001:1001 .
```

**Comment by klys** [comment]
I solved it by giving the underlying folder 777 permission
