### ISSUE TITLE
gulp trust-dev-cert from PowerShell Windows 10

### ISSUE THREAD

**Issue by FaganSC** [waldekmastykarz/docker-spfx#29]
I'm getting the following error message when I try to run gulp trust-dev-cert from PowerShell Windows 10. I have tried SPFx 1.8.2 and SPFx 1.7.0 and I receive the message with both images. Is there something I'm missing?

```
spfx@cfc024890ffa:/usr/app/spfx$ gulp trust-dev-cert
module.js:550
    throw err;
    ^

Error: Cannot find module '@microsoft/sp-build-web'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/app/spfx/gulpfile.js:4:15)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
spfx@cfc024890ffa:/usr/app/spfx$
```

**Comment by FaganSC** [comment]
Is this the same issue as #25 and #19 ?

**Comment by furtivesock** [comment]
Hello, I'm getting the same error as you. Were you able to solve it ?
