### ISSUE TITLE
Permission Denied - Missing write access to /usr/app/spfx

### ISSUE THREAD

**Issue by garrytrinder** [waldekmastykarz/docker-spfx#42]
Running on Ubuntu 20.04 in WSL2.

Docker container started from the SPFx solution root folder using...

```sh
docker run -it --rm --name ${PWD##*/} -v $PWD:/usr/app/spfx -p 5432:5432 -p 4321:4321 -p 35729:35729 waldekm/spfx:1.11.0
```

When running `npm i`, error is thrown...

```sh
npm WARN checkPermissions Missing write access to /usr/app/spfx
npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /usr/app/spfx
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/usr/app/spfx'
npm ERR!  { [Error: EACCES: permission denied, access '/usr/app/spfx']
npm ERR!   stack: 'Error: EACCES: permission denied, access \'/usr/app/spfx\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/app/spfx' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/spfx/.npm/_logs/2020-12-10T12_45_58_532Z-debug.log
```

Any ideas?

**Comment by waldekmastykarz** [comment]
Have you configured docker to have write permissions to the mounted folder on your host?

**Comment by garrytrinder** [comment]
Interesting, hadn't thought of that, if I run the container as sudo and it works, then it would point to permissions being the issue. I'll check and get back to you.

**Comment by garrytrinder** [comment]
Running the container as `sudo` doesn't seem to make a difference. I am running Docker on Ubuntu 20 in WSL2 though, so maybe there is something in there not quite right.

I'll check my Ubuntu desktop and see if I can replicate the issue.

**Comment by garrytrinder** [comment]
Ok, so I tried the `:latest` image on Ubuntu but this time running from an empty folder, so using the container to scaffold a new SPFx project using the generator and got a `permission denied` error attempting to create the `package.json` file. So looks like its the same issue.

![image](https://user-images.githubusercontent.com/11563347/102415370-f4b26e00-3fef-11eb-9125-b398db108a46.png)

```
  create package.json

     _-----_     ╭───────────────────────╮
    |       |    │      Bye from us!     │
    |--(o)--|    │       Chat soon.      │
   `---------´   │      Yeoman team      │
    ( _´U`_ )    │    http://yeoman.io   │
    /___A___\   /╰───────────────────────╯
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

fs.js:114
    throw err;
    ^

Error: EACCES: permission denied, open '/usr/app/spfx/package.json'
    at Object.openSync (fs.js:443:3)
    at Object.writeFileSync (fs.js:1194:35)
    at write (/usr/local/lib/node_modules/@microsoft/generator-sharepoint/node_modules/mem-fs-editor/lib/actions/commit.js:14:6)
    at DestroyableTransform._transform (/usr/local/lib/node_modules/@microsoft/generator-sharepoint/node_modules/mem-fs-editor/lib/actions/commit.js:43:7)
    at DestroyableTransform.Transform._read (/usr/local/lib/node_modules/@microsoft/generator-sharepoint/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/usr/local/lib/node_modules/@microsoft/generator-sharepoint/node_modules/readable-stream/lib/_stream_transform.js:172:83)
    at doWrite (/usr/local/lib/node_modules/@microsoft/generator-sharepoint/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/usr/local/lib/node_modules/@microsoft/generator-sharepoint/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at DestroyableTransform.Writable.write (/usr/local/lib/node_modules/@microsoft/generator-sharepoint/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at DestroyableTransform.ondata (/usr/local/lib/node_modules/@microsoft/generator-sharepoint/node_modules/readable-stream/lib/_stream_readable.js:619:20)
```

**Comment by waldekmastykarz** [comment]
> Interesting, hadn't thought of that, if I run the container as sudo and it works, then it would point to permissions being the issue. I'll check and get back to you.

I'm not sure if that's the case though. Did you have a look at the file sharing docs? https://docs.docker.com/docker-for-mac/#file-sharing

**Comment by garrytrinder** [comment]
Ok so its running perfectly fine for me on MacOS, I'll close this as its clearly an issue with Ubuntu docker setup.

Thanks for you help @waldekmastykarz I'll close this issue as its not an issue with your docker image.
